#:schema node_modules/wrangler/config-schema.json

name = "social-media-client"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-07-18"

[vars]
NODE_VERSION = "20.14.0"
PNPM_VERSION = "9.4.0"
DISCORD_SERVER_ID = "1155559296176758855"
DISCORD_VALID_ROLE_IDS = ["1155559423394197635", "1155559738063458444"]

[[d1_databases]]
binding = "DB"
database_name = "rtainjapan-social-media"
database_id = "86a823ea-35dd-4a2a-b9d1-c48c56674ad2"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "36a1ae0ce12045c8bc89416a4f84eff3"
